export const TIMESLOT_REQUEST = 'TIMESLOT_REQUEST';
export const TIMESLOT_SUCCESS = 'TIMESLOT_SUCCESS';
export const TIMESLOT_FAIL = 'TIMESLOT_FAIL';
export const TIMESLOT_ADD = 'TIMESLOT_ADD';
export const TIMESLOT_REMOVE = 'TIMESLOT_REMOVE';
export const TIMESLOT_UPDATE = 'TIMESLOT_UPDATE';
